sudo: false
dist: trusty
language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
addons:
  apt:
    packages:
      - stunnel
before_install:
    - composer install
script:
    - ./vendor/bin/phpunit
